-- begin STORE_ORDER_POSITION
alter table STORE_ORDER_POSITION add constraint FK_STORE_ORDER_POSITION_ON_PRODUCT foreign key (PRODUCT_ID) references STORE_PRODUCT(ID)^
alter table STORE_ORDER_POSITION add constraint FK_STORE_ORDER_POSITION_ON_ORDER foreign key (ORDER_ID) references STORE_ORDER(ID)^
create index IDX_STORE_ORDER_POSITION_ON_PRODUCT on STORE_ORDER_POSITION (PRODUCT_ID)^
create index IDX_STORE_ORDER_POSITION_ON_ORDER on STORE_ORDER_POSITION (ORDER_ID)^
-- end STORE_ORDER_POSITION
-- begin STORE_PRODUCT
create unique index IDX_STORE_PRODUCT_UNIQ_NAME on STORE_PRODUCT (NAME)^
-- end STORE_PRODUCT
-- begin STORE_ORDER
alter table STORE_ORDER add constraint FK_STORE_ORDER_ON_CLIENT foreign key (CLIENT_ID) references STORE_CLIENT(ID)^
create unique index IDX_STORE_ORDER_UNIQ_ORDER_NUMBER on STORE_ORDER (ORDER_NUMBER)^
create index IDX_STORE_ORDER_ON_CLIENT on STORE_ORDER (CLIENT_ID)^
-- end STORE_ORDER
