alter table STORE_ORDER add constraint FK_STORE_ORDER_ON_ORDER_POSITIONS foreign key (ORDER_POSITIONS_ID) references STORE_ORDER_POSITION(ID);
create index IDX_STORE_ORDER_ON_ORDER_POSITIONS on STORE_ORDER (ORDER_POSITIONS_ID);
